### PR TITLE
added total hours to output

### PR DESCRIPTION
**Pull request by fabean**
Thought it would be nice to output the total hours in your tracker.

### CODE REVIEW

**Comment by fabean** [comment]
Currently doesn't output right if you only have one tracker, should be easy enough to fix.

**Comment by fabean** [comment]
Latest push of including `elapsed` fixed that issue.

**Review by derhuerst — CHANGES_REQUESTED** [review]
Having `totalTime` as global state is dangerous. Please move it into `status`.

**Comment by derhuerst** [comment]
@fabean ping 😉

**Comment by fabean** [comment]
@derhuerst made that change. Had to refactor a little bit to pass that variable around.

**Comment by fabean** [comment]
Also if you want both my changes from https://github.com/derhuerst/time-tracking/pull/26 the total times should be updated to be pretty printed as well.

**Comment by derhuerst** [comment]
Thanks. I still would like to change things though:

- It prints the "Total Time: ..." message even if I use the `--porcelain` option for JSON.
- I'd like to avoid passing `totalTime` into `statusOfTracker`.
- It prints the total time even if I want to show only one tracker.

I will amend your commits and merge.

**Pull request closed without merging**
